use super::{
    Assignment, Attr, BinaryOp, Delimited, Key, LetBinding, MapKind,
    Matcher, MatcherKind, ObjectMatcher, PbNode, PbNodeKind,
    Span, SwitchCase, UnaryOp,
    lexer::{
        Tok,
        LexError,
    }
};
use crate::strkey::StrKey;
grammar<F>(f: &F);

extern {
    type Location = usize;
    type Error = LexError;

    enum Tok {
        "bind"      => Tok::Bind,
        "let"       => Tok::Let,
        "in"        => Tok::In,
        "if"        => Tok::If,
        "for"       => Tok::For,
        "switch"    => Tok::Switch,
        "null"      => Tok::Null,
        "true"      => Tok::True,
        "false"     => Tok::False,
        "@"         => Tok::At,
        "_"         => Tok::Underscore,
        "..."       => Tok::TripleDots,
        "=>"        => Tok::RDoubleArrow,
        ":"         => Tok::Colon,
        ";"         => Tok::SemiColon,
        "="         => Tok::Assign,
        "|"         => Tok::Pipe,
        "."         => Tok::Dot,
        ","         => Tok::Comma,
        "-"         => Tok::Minus,
        "!"         => Tok::UnOpNot,
        "?"         => Tok::BinOpHasAttr,
        "++"        => Tok::BinOpListConcat,
        "*"         => Tok::BinOpMult,
        "/"         => Tok::BinOpDiv,
        "+"         => Tok::BinOpAdd,
        "//"        => Tok::BinOpUpdate,
        "<"         => Tok::BinOpLt,
        "<="        => Tok::BinOpLe,
        ">"         => Tok::BinOpGt,
        ">="        => Tok::BinOpGe,
        "=="        => Tok::BinOpEq,
        "!="        => Tok::BinOpNeq,
        "&&"        => Tok::BinOpLogAnd,
        "||"        => Tok::BinOpLogOr,
        "->"        => Tok::BinOpLogImpl,
        "{"         => Tok::LBrace,
        "}"         => Tok::RBrace,
        "("         => Tok::LPar,
        ")"         => Tok::RPar,
        "["         => Tok::LSqBracket,
        "]"         => Tok::RSqBracket,

        "ident"     => Tok::Ident(<StrKey>),
        "num"       => Tok::Number(<String>),
        "str"       => Tok::Str(<String>),
    }
}

pub Expr: PbNode = {
    <ExprBindBlocks>,
};

ExprBindBlocks: PbNode = {
    <l:@L> "let" <s:LetSetStmt*> "in" <e:ExprBindBlocks> <r:@R> =>
        PbNode::new(PbNodeKind::Let(s, Box::new(e)), l, r, f),
    <l:@L> "bind" <s:BindSetStmt*> "in" <e:ExprBindBlocks> <r:@R> =>
        PbNode::new(PbNodeKind::Bind(s, Box::new(e)), l, r, f),
    <l:@L> "|" <ms:Matcher*> "|" <e:ExprBindBlocks> <r:@R> =>
        PbNode::new(PbNodeKind::FuncDef(ms, Box::new(e)), l, r, f),
    <ExprLogImpl>,
};

ExprLogImpl: PbNode = {
    <l:@L> <lhs:ExprLogImpl> "->" <rhs:ExprLogOr> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::LogImpl, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <ExprLogOr>,
};
ExprLogOr: PbNode = {
    <l:@L> <lhs:ExprLogOr> "||" <rhs:ExprLogAnd> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::LogOr, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <ExprLogAnd>,
};
ExprLogAnd: PbNode = {
    <l:@L> <lhs:ExprLogAnd> "&&" <rhs:ExprEq> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::LogAnd, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <ExprEq>,
};
ExprEq: PbNode = {
    <l:@L> <lhs:ExprCompare> "==" <rhs:ExprCompare> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::Eq, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <l:@L> <lhs:ExprCompare> "!=" <rhs:ExprCompare> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::Neq, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <ExprCompare>,
};
ExprCompare: PbNode = {
    <l:@L> <lhs:ExprUpdate> "<" <rhs:ExprUpdate> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::Lt, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <l:@L> <lhs:ExprUpdate> "<=" <rhs:ExprUpdate> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::Le, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <l:@L> <lhs:ExprUpdate> ">" <rhs:ExprUpdate> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::Gt, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <l:@L> <lhs:ExprUpdate> ">=" <rhs:ExprUpdate> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::Ge, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <ExprUpdate>,
};
ExprUpdate: PbNode = {
    <l:@L> <lhs:ExprUpdate> "//" <rhs:ExprNot> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::Update, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <ExprNot>,
};
ExprNot: PbNode = {
    <l:@L> "!" <rhs:ExprAddSub> <r:@R> =>
        PbNode::new(PbNodeKind::Unary(UnaryOp::Not, Box::new(rhs)), l, r, f),
    <ExprAddSub>,
};
ExprAddSub: PbNode = {
    <l:@L> <lhs:ExprAddSub> "-" <rhs:ExprMultDiv> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::Sub, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <l:@L> <lhs:ExprAddSub> "+" <rhs:ExprMultDiv> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::Add, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <ExprMultDiv>,
};
ExprMultDiv: PbNode = {
    <l:@L> <lhs:ExprMultDiv> "*" <rhs:ExprConcat> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::Mult, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <l:@L> <lhs:ExprMultDiv> "/" <rhs:ExprConcat> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::Div, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <ExprConcat>,
};
ExprConcat: PbNode = {
    <l:@L> <lhs:ExprConcat> "++" <rhs:ExprHasAttr> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::ListConcat, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <ExprHasAttr>,
};
ExprHasAttr: PbNode = {
    <l:@L> <lhs:ExprNeg> "?" <rhs:ExprNeg> <r:@R> =>
        PbNode::new(
            PbNodeKind::Binary(BinaryOp::HasAttr, Box::new(lhs), Box::new(rhs)),
            l, r, f,
        ),
    <ExprNeg>,
};
ExprNeg: PbNode = {
    <l:@L> "-" <rhs:ExprFuncCall> <r:@R> =>
        PbNode::new(PbNodeKind::Unary(UnaryOp::Neg, Box::new(rhs)), l, r, f),
    <ExprFuncCall>,
};
ExprFuncCall: PbNode = {
    <l:@L> <func:ExprFuncCall> <arg:ExprAttrSel> <r:@R> =>
        PbNode::new(PbNodeKind::FuncCall(Box::new(func), Box::new(arg)), l, r, f),
    <ExprAttrSel>,
};
ExprAttrSel: PbNode = {
    <l:@L> <lhs:ExprAttrSel> "." <li:@L> <rhs:Ident> <r:@R> =>
        PbNode::new(
            PbNodeKind::AttrSel(
                Box::new(lhs),
                Attr::Ident(rhs, Some(Span { start: li, end: r })),
            ),
            l, r, f,
        ),
    <l:@L> <lhs:ExprAttrSel> "." "{" <rhs:Expr> "}" <r:@R> =>
        PbNode::new(
            PbNodeKind::AttrSel(Box::new(lhs), Attr::Dynamic(Box::new(rhs))),
            l, r, f,
        ),
    <ExprListComp>,
};
ExprListComp: PbNode = {
    <l:@L> "(" <func:Expr> "for" <init:(<Expr> ":")?> <source:Expr>
        ")" <r:@R> =>
        PbNode::new(
            PbNodeKind::Fold {
                func: Box::new(func),
                init: init.map(Box::new),
                input: Box::new(source),
            },
            l, r, f,
        ),
    <l:@L> "[" <func:Expr> "for" <source:Expr>
        <filter:("if" <Expr>)?> "]" <r:@R> =>
        PbNode::new(
            PbNodeKind::Map {
                kind: MapKind::List,
                func: Box::new(func),
                input: Box::new(source),
                filter: filter.map(Box::new),
            },
            l, r, f,
        ),
    <l:@L> "{" <func:Expr> "for" <source:Expr>
        <filter:("if" <Expr>)?> "}" <r:@R> =>
        PbNode::new(
            PbNodeKind::Map {
                kind: MapKind::Object,
                func: Box::new(func),
                input: Box::new(source),
                filter: filter.map(Box::new),
            },
            l, r, f,
        ),
    <ExprSwitch>,
};
ExprSwitch: PbNode = {
    <l:@L> "switch" <source:ExprTerm> "{" <cases:SwitchCase*>
        <default:("_" "=>" <Expr> ";")?> "}" <r:@R> =>
        PbNode::new(
            PbNodeKind::Switch {
                input: Box::new(source),
                cases,
                default: default.map(Box::new),
            },
            l, r, f,
        ),
    <ExprTerm>,
};
SwitchCase: SwitchCase =
    <l:@L> <matcher:Expr> "=>" <value:Expr> ";" <r:@R> =>
        SwitchCase {
            matcher,
            value,
            span: Some(Span { start: l, end: r }),
        };

ExprTerm: PbNode = {
    <ExprObject>,
    <ExprList>,
    <ExprTuple>,
    <ExprValue>,
    <ExprVar>,
    <ExprNull>,
    <l:@L> "(" <value:Expr> ")" <r:@R> =>
        PbNode::new(PbNodeKind::Group(Box::new(value)), l, r, f),
};
ExprObject: PbNode =
    <l:@L> "{" <items:AssignStmt*> "}" <r:@R> =>
        PbNode::new(PbNodeKind::Object(items), l, r, f);
ExprList: PbNode =
    <l:@L> "[" <items:Comma<Expr>> "]" <r:@R> =>
        PbNode::new(PbNodeKind::List(items), l, r, f);
ExprTuple: PbNode =
    <l:@L> "(" <items:TupleComma<Expr>> ")" <r:@R> =>
        PbNode::new(PbNodeKind::Tuple(items), l, r, f);

LetSetStmt: LetBinding =
    <l:@L> <matcher:Matcher> "=" <value:Expr> ";" <r:@R> =>
        LetBinding {
            matcher,
            value,
            span: Some(Span { start: l, end: r }),
        };
BindSetStmt: Assignment =
    <l:@L> <key:Ident> "=" <value:Expr> ";" <r:@R> =>
        Assignment {
            key: Key::Ident(key, Some(Span { start: l, end: r })),
            value,
            span: Some(Span { start: l, end: r }),
        };
AssignStmt: Assignment = {
    <l:@L> <key:Ident> "=" <value:Expr> ";" <r:@R> =>
        Assignment {
            key: Key::Ident(key, Some(Span { start: l, end: r })),
            value,
            span: Some(Span { start: l, end: r }),
        },
    <l:@L> <key:RawString> "=" <value:Expr> ";" <r:@R> =>
        Assignment {
            key: Key::String(key, Some(Span { start: l, end: r })),
            value,
            span: Some(Span { start: l, end: r }),
        },
};
ExprVar: PbNode =
    <l:@L> <name:Ident> <r:@R> => PbNode::new(PbNodeKind::Var(name), l, r, f);
ExprNull: PbNode =
    <l:@L> "null" <r:@R> => PbNode::new(PbNodeKind::Null, l, r, f);

Matcher: Matcher = {
    <l:@L> <matcher:MatcherInner> "@" <name:Ident> <r:@R> =>
        Matcher::new(
            MatcherKind::Alias(
                Box::new(matcher), name,
                Some(Span { start: l, end: r }),
            ),
            l, r, f,
        ),
    <MatcherInner>,
};
MatcherInner: Matcher = {
    <l:@L> <name:Ident> <r:@R> => Matcher::new(MatcherKind::Ident(name), l, r, f),
    <l:@L> "_" <r:@R> => Matcher::new(MatcherKind::DontCare, l, r, f),
    <l:@L> "(" <items:TupleComma<Matcher>> ")" <r:@R> =>
        Matcher::new(MatcherKind::Tuple(items), l, r, f),
    <l:@L> "{" <mut fields:(<ObjectMatcher> ",")*>
        <last:ObjectMatcher?> "}" <r:@R> => {
        if let Some(last) = last {
            fields.push(last);
        }
        Matcher::new(MatcherKind::Object { fields, exhaustive: true }, l, r, f)
    },
    <l:@L> "{" <fields:(<ObjectMatcher> ",")*> "..." "}" <r:@R> =>
        Matcher::new(MatcherKind::Object { fields, exhaustive: false }, l, r, f),
};
ObjectMatcher: ObjectMatcher = {
    <l:@L> <key:Ident> <r:@R> => ObjectMatcher {
        key,
        matcher: Matcher::new(MatcherKind::Ident(key), l, r, f),
        default: None,
        span: Some(Span { start: l, end: r }),
    },
    <l:@L> <key:Ident> "=" <matcher:Matcher> <r:@R> => ObjectMatcher {
        key,
        matcher,
        default: None,
        span: Some(Span { start: l, end: r }),
    },
    <l:@L> <key:Ident> "?" <default:ExprTerm> <r:@R> => ObjectMatcher {
        key,
        matcher: Matcher::new(MatcherKind::Ident(key), l, r, f),
        default: Some(default),
        span: Some(Span { start: l, end: r }),
    },
    <l:@L> <key:Ident> "=" <matcher:Matcher> "?" <default:ExprTerm>
        <r:@R> => ObjectMatcher {
            key,
            matcher,
            default: Some(default),
            span: Some(Span { start: l, end: r }),
        },
};

Ident: StrKey = <s:"ident"> => s;
ExprValue: PbNode = {
    <l:@L> "true" <r:@R> => PbNode::new(PbNodeKind::Bool(true), l, r, f),
    <l:@L> "false" <r:@R> => PbNode::new(PbNodeKind::Bool(false), l, r, f),
    <l:@L> <value:"num"> <r:@R> =>
        PbNode::new(PbNodeKind::Int(value), l, r, f),
    <l:@L> <value:RawString> <r:@R> =>
        PbNode::new(PbNodeKind::String(value), l, r, f),
};
RawString: String = <s:"str"> => s;

Comma<T>: Delimited<T> = {
    <mut values:(<T> ",")*> <last:T?> => match last {
        None => {
            let trailing = !values.is_empty();
            Delimited { items: values, trailing }
        }
        Some(last) => {
            values.push(last);
            Delimited { items: values, trailing: false }
        }
    },
};
TupleComma<T>: Delimited<T> = {
    "," => Delimited { items: vec![], trailing: true },
    <mut values:(<T> ",")+> <last:T?> => match last {
        None => Delimited { items: values, trailing: true },
        Some(last) => {
            values.push(last);
            Delimited { items: values, trailing: false }
        }
    },
};
